resource "google_project_iam_custom_role" "clickhouse_common_role" {
  role_id     = "clickhouseCommonRole"
  title       = "ClickHouse Common Role"
  description = "Role to allow ClickHouse Cloud common operations"
  permissions = [
    # Regional Operations
    "compute.regions.get",
    "compute.regions.list",

    # Zone Operations
    "compute.zones.get",
    "compute.zones.list",

    # General service account operations
    "iam.serviceAccounts.actAs",
    "iam.serviceAccounts.get",

    # Project operations
    "resourcemanager.projects.get",

    # Service usage for validation checks
    "serviceusage.services.get",
  ]
}

# Always granted. Covers what ClickHouse needs even in a bring-your-own-VPC
# setup: read/observe and use the VPC and related resources, plus create and
# manage the ClickHouse-owned resources it provisions inside the VPC (in the
# service project) regardless of who owns the network — the PrivateLink (PSC)
# service attachment and the ingress/static IP addresses. The customer's own
# network topology (networks, routes, Cloud Routers, subnets) lives in
# clickhouseVPCWriteRole, gated by var.include_vpc_write_permissions.
#
# addresses create+delete stay here (not in the write role) because ClickHouse
# creates ingress IPs in the service project even when the customer brings
# their own VPC; GCP IAM cannot scope those verbs to only the ClickHouse-owned
# instances, and gating them breaks ingress load balancers under
# bring-your-own-VPC. Subnets are not in that category: since BYOC-891 the
# customer pre-creates the PSC NAT subnet and the composition observes every
# subnet under bring-your-own-VPC, so ClickHouse creates none.
resource "google_project_iam_custom_role" "clickhouse_vpc_role" {
  role_id     = "clickhouseVPCRole"
  title       = "ClickHouse VPC Role"
  description = "Role to allow ClickHouse Cloud to read and use VPC resources in your project, and to manage the ClickHouse-owned addresses and PrivateLink (PSC) service attachment it provisions within the VPC"
  permissions = [
    # Network
    "compute.networks.access",
    "compute.networks.get",
    "compute.networks.getEffectiveFirewalls",
    "compute.networks.getRegionEffectiveFirewalls",
    "compute.networks.list",
    "compute.networks.listEffectiveTags",
    "compute.networks.listPeeringRoutes",
    "compute.networks.listTagBindings",
    "compute.networks.use",
    "compute.networks.useExternalIp",
    "compute.networks.updatePolicy",

    # Private Service Connect
    "compute.serviceAttachments.get",
    "compute.serviceAttachments.delete",
    "compute.serviceAttachments.create",
    "compute.serviceAttachments.list",
    "compute.serviceAttachments.update",
    "compute.forwardingRules.use",
    "compute.regionOperations.get",

    # Subnetwork — read/use only. Creating and deleting subnets is a
    # ClickHouse-managed-VPC concern and lives in clickhouseVPCWriteRole.
    "compute.subnetworks.get",
    "compute.subnetworks.getIamPolicy",
    "compute.subnetworks.list",
    "compute.subnetworks.listEffectiveTags",
    "compute.subnetworks.listTagBindings",
    "compute.subnetworks.use",
    "compute.subnetworks.useExternalIp",
    "compute.subnetworks.usePeerMigration",

    # Route
    "compute.routes.get",
    "compute.routes.list",
    "compute.routes.listEffectiveTags",
    "compute.routes.listTagBindings",

    # Router (Cloud Router)
    "compute.routers.get",
    "compute.routers.getRoutePolicy",
    "compute.routers.list",
    "compute.routers.listBgpRoutes",
    "compute.routers.listEffectiveTags",
    "compute.routers.listRoutePolicies",
    "compute.routers.listTagBindings",
    "compute.routers.use",

    # Address (Static IPs) — read/use, plus create/delete for the
    # ClickHouse-owned ingress/static IPs created in the service project (also
    # under bring-your-own-VPC)
    "compute.addresses.create",
    "compute.addresses.createInternal",
    "compute.addresses.delete",
    "compute.addresses.deleteInternal",
    "compute.addresses.get",
    "compute.addresses.list",
    "compute.addresses.listEffectiveTags",
    "compute.addresses.listTagBindings",
    "compute.addresses.setLabels",
    "compute.addresses.use",
    "compute.addresses.useInternal",
  ]
}

# Create/delete/modify permissions for the customer's VPC network topology:
# the networks themselves, routes, Cloud Routers (Cloud NAT), and subnets
# (lifecycle plus attributes — IAM policy, CIDR expansion, private Google
# access, tag bindings). Gated by var.include_vpc_write_permissions: set it to
# false for bring-your-own-VPC onboarding, where the customer pre-creates and
# manages these resources. The role is only created and bound when writes are
# enabled.
#
# Note: addresses create+delete are deliberately NOT gated here — ClickHouse
# must still create its own ingress IPs in the service project even under
# bring-your-own-VPC. Those live in clickhouseVPCRole.
resource "google_project_iam_custom_role" "clickhouse_vpc_write_role" {
  count = var.include_vpc_write_permissions ? 1 : 0

  role_id     = "clickhouseVPCWriteRole"
  title       = "ClickHouse VPC Write Role"
  description = "Role to allow ClickHouse Cloud to create, delete, and modify the VPC network topology (networks, routes, Cloud Routers, and subnets) in your project"
  permissions = [
    # Network
    "compute.networks.addPeering",
    "compute.networks.create",
    "compute.networks.createTagBinding",
    "compute.networks.delete",
    "compute.networks.deleteTagBinding",
    "compute.networks.mirror",
    "compute.networks.removePeering",
    "compute.networks.setFirewallPolicy",
    "compute.networks.switchToCustomMode",
    "compute.networks.update",
    "compute.networks.updatePeering",

    # Subnetwork (lifecycle + attribute management)
    "compute.subnetworks.create",
    "compute.subnetworks.createTagBinding",
    "compute.subnetworks.delete",
    "compute.subnetworks.deleteTagBinding",
    "compute.subnetworks.expandIpCidrRange",
    "compute.subnetworks.mirror",
    "compute.subnetworks.setIamPolicy",
    "compute.subnetworks.setPrivateIpGoogleAccess",
    "compute.subnetworks.update",

    # Route
    "compute.routes.create",
    "compute.routes.createTagBinding",
    "compute.routes.delete",
    "compute.routes.deleteTagBinding",

    # Router (Cloud Router)
    "compute.routers.create",
    "compute.routers.createTagBinding",
    "compute.routers.delete",
    "compute.routers.deleteRoutePolicy",
    "compute.routers.deleteTagBinding",
    "compute.routers.update",
    "compute.routers.updateRoutePolicy",

    # Address (tag bindings; create/delete stay in clickhouseVPCRole)
    "compute.addresses.createTagBinding",
    "compute.addresses.deleteTagBinding",
  ]
}

resource "google_project_iam_custom_role" "clickhouse_cluster_role" {
  role_id     = "clickhouseClusterRole"
  title       = "ClickHouse Cluster Role"
  description = "Role to allow ClickHouse Cloud to manage cluster resources in your project"
  permissions = [
    # GKE
    "container.clusters.connect",
    "container.clusters.create",
    "container.clusters.createTagBinding",
    "container.clusters.delete",
    "container.clusters.deleteTagBinding",
    "container.clusters.get",
    "container.clusters.getCredentials",
    "container.clusters.impersonate",
    "container.clusters.list",
    "container.clusters.listEffectiveTags",
    "container.clusters.listTagBindings",
    "container.clusters.update",
    "container.operations.get",
    "container.operations.list",

    # GKE Nodes
    "container.nodes.create",
    "container.nodes.delete",
    "container.nodes.get",
    "container.nodes.getStatus",
    "container.nodes.list",
    "container.nodes.proxy",
    "container.nodes.update",
    "container.nodes.updateStatus",

    # Instance Group Manager (Node Groups)
    "compute.instanceGroupManagers.get",
    "compute.instanceGroupManagers.list",
    "compute.instanceGroupManagers.listEffectiveTags",
    "compute.instanceGroupManagers.listTagBindings",
    "compute.instanceGroupManagers.update",
    "compute.instanceGroupManagers.use",

    # Manage in-cluster resources (requires  {APIGroups:["*"], Resources:["*"], Verbs:["*"]} in order to create ArgoCD KSA)
    "container.apiServices.create",
    "container.apiServices.delete",
    "container.apiServices.get",
    "container.apiServices.getStatus",
    "container.apiServices.list",
    "container.apiServices.update",
    "container.apiServices.updateStatus",
    "container.auditSinks.create",
    "container.auditSinks.delete",
    "container.auditSinks.get",
    "container.auditSinks.list",
    "container.auditSinks.update",
    "container.backendConfigs.create",
    "container.backendConfigs.delete",
    "container.backendConfigs.get",
    "container.backendConfigs.list",
    "container.backendConfigs.update",
    "container.bindings.create",
    "container.bindings.delete",
    "container.bindings.get",
    "container.bindings.list",
    "container.bindings.update",
    "container.certificateSigningRequests.approve",
    "container.certificateSigningRequests.create",
    "container.certificateSigningRequests.delete",
    "container.certificateSigningRequests.get",
    "container.certificateSigningRequests.getStatus",
    "container.certificateSigningRequests.list",
    "container.certificateSigningRequests.update",
    "container.certificateSigningRequests.updateStatus",
    "container.clusterRoleBindings.create",
    "container.clusterRoleBindings.delete",
    "container.clusterRoleBindings.get",
    "container.clusterRoleBindings.list",
    "container.clusterRoleBindings.update",
    "container.clusterRoles.bind",
    "container.clusterRoles.create",
    "container.clusterRoles.delete",
    "container.clusterRoles.escalate",
    "container.clusterRoles.get",
    "container.clusterRoles.list",
    "container.clusterRoles.update",
    "container.componentStatuses.get",
    "container.componentStatuses.list",
    "container.configMaps.create",
    "container.configMaps.delete",
    "container.configMaps.get",
    "container.configMaps.list",
    "container.configMaps.update",
    "container.controllerRevisions.create",
    "container.controllerRevisions.delete",
    "container.controllerRevisions.get",
    "container.controllerRevisions.list",
    "container.controllerRevisions.update",
    "container.cronJobs.create",
    "container.cronJobs.delete",
    "container.cronJobs.get",
    "container.cronJobs.getStatus",
    "container.cronJobs.list",
    "container.cronJobs.update",
    "container.cronJobs.updateStatus",
    "container.csiDrivers.create",
    "container.csiDrivers.delete",
    "container.csiDrivers.get",
    "container.csiDrivers.list",
    "container.csiDrivers.update",
    "container.csiNodeInfos.create",
    "container.csiNodeInfos.delete",
    "container.csiNodeInfos.get",
    "container.csiNodeInfos.list",
    "container.csiNodeInfos.update",
    "container.csiNodes.create",
    "container.csiNodes.delete",
    "container.csiNodes.get",
    "container.csiNodes.list",
    "container.csiNodes.update",
    "container.customResourceDefinitions.create",
    "container.customResourceDefinitions.delete",
    "container.customResourceDefinitions.get",
    "container.customResourceDefinitions.getStatus",
    "container.customResourceDefinitions.list",
    "container.customResourceDefinitions.update",
    "container.customResourceDefinitions.updateStatus",
    "container.daemonSets.create",
    "container.daemonSets.delete",
    "container.daemonSets.get",
    "container.daemonSets.getStatus",
    "container.daemonSets.list",
    "container.daemonSets.update",
    "container.daemonSets.updateStatus",
    "container.deployments.create",
    "container.deployments.delete",
    "container.deployments.get",
    "container.deployments.getScale",
    "container.deployments.getStatus",
    "container.deployments.list",
    "container.deployments.rollback",
    "container.deployments.update",
    "container.deployments.updateScale",
    "container.deployments.updateStatus",
    "container.endpointSlices.create",
    "container.endpointSlices.delete",
    "container.endpointSlices.get",
    "container.endpointSlices.list",
    "container.endpointSlices.update",
    "container.endpoints.create",
    "container.endpoints.delete",
    "container.endpoints.get",
    "container.endpoints.list",
    "container.endpoints.update",
    "container.events.create",
    "container.events.delete",
    "container.events.get",
    "container.events.list",
    "container.events.update",
    "container.frontendConfigs.create",
    "container.frontendConfigs.delete",
    "container.frontendConfigs.get",
    "container.frontendConfigs.list",
    "container.frontendConfigs.update",
    "container.horizontalPodAutoscalers.create",
    "container.horizontalPodAutoscalers.delete",
    "container.horizontalPodAutoscalers.get",
    "container.horizontalPodAutoscalers.getStatus",
    "container.horizontalPodAutoscalers.list",
    "container.horizontalPodAutoscalers.update",
    "container.horizontalPodAutoscalers.updateStatus",
    "container.ingresses.create",
    "container.ingresses.delete",
    "container.ingresses.get",
    "container.ingresses.getStatus",
    "container.ingresses.list",
    "container.ingresses.update",
    "container.ingresses.updateStatus",
    "container.initializerConfigurations.create",
    "container.initializerConfigurations.delete",
    "container.initializerConfigurations.get",
    "container.initializerConfigurations.list",
    "container.initializerConfigurations.update",
    "container.jobs.create",
    "container.jobs.delete",
    "container.jobs.get",
    "container.jobs.getStatus",
    "container.jobs.list",
    "container.jobs.update",
    "container.jobs.updateStatus",
    "container.leases.create",
    "container.leases.delete",
    "container.leases.get",
    "container.leases.list",
    "container.leases.update",
    "container.limitRanges.create",
    "container.limitRanges.delete",
    "container.limitRanges.get",
    "container.limitRanges.list",
    "container.limitRanges.update",
    "container.localSubjectAccessReviews.create",
    "container.localSubjectAccessReviews.list",
    "container.managedCertificates.create",
    "container.managedCertificates.delete",
    "container.managedCertificates.get",
    "container.managedCertificates.list",
    "container.managedCertificates.update",
    "container.mutatingWebhookConfigurations.create",
    "container.mutatingWebhookConfigurations.delete",
    "container.mutatingWebhookConfigurations.get",
    "container.mutatingWebhookConfigurations.list",
    "container.mutatingWebhookConfigurations.update",
    "container.namespaces.create",
    "container.namespaces.delete",
    "container.namespaces.finalize",
    "container.namespaces.get",
    "container.namespaces.getStatus",
    "container.namespaces.list",
    "container.namespaces.update",
    "container.namespaces.updateStatus",
    "container.networkPolicies.create",
    "container.networkPolicies.delete",
    "container.networkPolicies.get",
    "container.networkPolicies.list",
    "container.networkPolicies.update",
    "container.nodes.create",
    "container.nodes.delete",
    "container.nodes.get",
    "container.nodes.getStatus",
    "container.nodes.list",
    "container.nodes.proxy",
    "container.nodes.update",
    "container.nodes.updateStatus",
    "container.persistentVolumeClaims.create",
    "container.persistentVolumeClaims.delete",
    "container.persistentVolumeClaims.get",
    "container.persistentVolumeClaims.getStatus",
    "container.persistentVolumeClaims.list",
    "container.persistentVolumeClaims.update",
    "container.persistentVolumeClaims.updateStatus",
    "container.persistentVolumes.create",
    "container.persistentVolumes.delete",
    "container.persistentVolumes.get",
    "container.persistentVolumes.getStatus",
    "container.persistentVolumes.list",
    "container.persistentVolumes.update",
    "container.persistentVolumes.updateStatus",
    "container.petSets.create",
    "container.petSets.delete",
    "container.petSets.get",
    "container.petSets.list",
    "container.petSets.update",
    "container.petSets.updateStatus",
    "container.podDisruptionBudgets.create",
    "container.podDisruptionBudgets.delete",
    "container.podDisruptionBudgets.get",
    "container.podDisruptionBudgets.getStatus",
    "container.podDisruptionBudgets.list",
    "container.podDisruptionBudgets.update",
    "container.podDisruptionBudgets.updateStatus",
    "container.podPresets.create",
    "container.podPresets.delete",
    "container.podPresets.get",
    "container.podPresets.list",
    "container.podPresets.update",
    "container.podSecurityPolicies.create",
    "container.podSecurityPolicies.delete",
    "container.podSecurityPolicies.get",
    "container.podSecurityPolicies.list",
    "container.podSecurityPolicies.update",
    "container.podSecurityPolicies.use",
    "container.podTemplates.create",
    "container.podTemplates.delete",
    "container.podTemplates.get",
    "container.podTemplates.list",
    "container.podTemplates.update",
    "container.pods.attach",
    "container.pods.create",
    "container.pods.delete",
    "container.pods.evict",
    "container.pods.exec",
    "container.pods.get",
    "container.pods.getLogs",
    "container.pods.getStatus",
    "container.pods.initialize",
    "container.pods.list",
    "container.pods.portForward",
    "container.pods.proxy",
    "container.pods.update",
    "container.pods.updateStatus",
    "container.priorityClasses.create",
    "container.priorityClasses.delete",
    "container.priorityClasses.get",
    "container.priorityClasses.list",
    "container.priorityClasses.update",
    "container.replicaSets.create",
    "container.replicaSets.delete",
    "container.replicaSets.get",
    "container.replicaSets.getScale",
    "container.replicaSets.getStatus",
    "container.replicaSets.list",
    "container.replicaSets.update",
    "container.replicaSets.updateScale",
    "container.replicaSets.updateStatus",
    "container.replicationControllers.create",
    "container.replicationControllers.delete",
    "container.replicationControllers.get",
    "container.replicationControllers.getScale",
    "container.replicationControllers.getStatus",
    "container.replicationControllers.list",
    "container.replicationControllers.update",
    "container.replicationControllers.updateScale",
    "container.replicationControllers.updateStatus",
    "container.resourceQuotas.create",
    "container.resourceQuotas.delete",
    "container.resourceQuotas.get",
    "container.resourceQuotas.getStatus",
    "container.resourceQuotas.list",
    "container.resourceQuotas.update",
    "container.resourceQuotas.updateStatus",
    "container.roleBindings.create",
    "container.roleBindings.delete",
    "container.roleBindings.get",
    "container.roleBindings.list",
    "container.roleBindings.update",
    "container.roles.bind",
    "container.roles.create",
    "container.roles.delete",
    "container.roles.escalate",
    "container.roles.get",
    "container.roles.list",
    "container.roles.update",
    "container.runtimeClasses.create",
    "container.runtimeClasses.delete",
    "container.runtimeClasses.get",
    "container.runtimeClasses.list",
    "container.runtimeClasses.update",
    "container.scheduledJobs.create",
    "container.scheduledJobs.delete",
    "container.scheduledJobs.get",
    "container.scheduledJobs.list",
    "container.scheduledJobs.update",
    "container.scheduledJobs.updateStatus",
    "container.secrets.create",
    "container.secrets.delete",
    "container.secrets.get",
    "container.secrets.list",
    "container.secrets.update",
    "container.selfSubjectAccessReviews.create",
    "container.selfSubjectAccessReviews.list",
    "container.selfSubjectRulesReviews.create",
    "container.serviceAccounts.create",
    "container.serviceAccounts.createToken",
    "container.serviceAccounts.delete",
    "container.serviceAccounts.get",
    "container.serviceAccounts.list",
    "container.serviceAccounts.update",
    "container.services.create",
    "container.services.delete",
    "container.services.get",
    "container.services.getStatus",
    "container.services.list",
    "container.services.proxy",
    "container.services.update",
    "container.services.updateStatus",
    "container.statefulSets.create",
    "container.statefulSets.delete",
    "container.statefulSets.get",
    "container.statefulSets.getScale",
    "container.statefulSets.getStatus",
    "container.statefulSets.list",
    "container.statefulSets.update",
    "container.statefulSets.updateScale",
    "container.statefulSets.updateStatus",
    "container.storageClasses.create",
    "container.storageClasses.delete",
    "container.storageClasses.get",
    "container.storageClasses.list",
    "container.storageClasses.update",
    "container.storageStates.create",
    "container.storageStates.delete",
    "container.storageStates.get",
    "container.storageStates.getStatus",
    "container.storageStates.list",
    "container.storageStates.update",
    "container.storageStates.updateStatus",
    "container.storageVersionMigrations.create",
    "container.storageVersionMigrations.delete",
    "container.storageVersionMigrations.get",
    "container.storageVersionMigrations.getStatus",
    "container.storageVersionMigrations.list",
    "container.storageVersionMigrations.update",
    "container.storageVersionMigrations.updateStatus",
    "container.subjectAccessReviews.create",
    "container.subjectAccessReviews.list",
    "container.thirdPartyObjects.create",
    "container.thirdPartyObjects.delete",
    "container.thirdPartyObjects.get",
    "container.thirdPartyObjects.list",
    "container.thirdPartyObjects.update",
    "container.thirdPartyResources.create",
    "container.thirdPartyResources.delete",
    "container.thirdPartyResources.get",
    "container.thirdPartyResources.list",
    "container.thirdPartyResources.update",
    "container.tokenReviews.create",
    "container.updateInfos.create",
    "container.updateInfos.delete",
    "container.updateInfos.get",
    "container.updateInfos.list",
    "container.updateInfos.update",
    "container.validatingWebhookConfigurations.create",
    "container.validatingWebhookConfigurations.delete",
    "container.validatingWebhookConfigurations.get",
    "container.validatingWebhookConfigurations.list",
    "container.validatingWebhookConfigurations.update",
    "container.volumeAttachments.create",
    "container.volumeAttachments.delete",
    "container.volumeAttachments.get",
    "container.volumeAttachments.getStatus",
    "container.volumeAttachments.list",
    "container.volumeAttachments.update",
    "container.volumeAttachments.updateStatus",
    "container.volumeSnapshotClasses.create",
    "container.volumeSnapshotClasses.delete",
    "container.volumeSnapshotClasses.get",
    "container.volumeSnapshotClasses.list",
    "container.volumeSnapshotClasses.update",
    "container.volumeSnapshotContents.create",
    "container.volumeSnapshotContents.delete",
    "container.volumeSnapshotContents.get",
    "container.volumeSnapshotContents.getStatus",
    "container.volumeSnapshotContents.list",
    "container.volumeSnapshotContents.update",
    "container.volumeSnapshotContents.updateStatus",
    "container.volumeSnapshots.create",
    "container.volumeSnapshots.delete",
    "container.volumeSnapshots.get",
    "container.volumeSnapshots.getStatus",
    "container.volumeSnapshots.list",
    "container.volumeSnapshots.update",
    "container.volumeSnapshots.updateStatus",
  ]
}

resource "google_project_iam_custom_role" "clickhouse_storage_role" {
  role_id     = "clickhouseStorageRole"
  title       = "ClickHouse Storage Role"
  description = "Role to allow ClickHouse Cloud to manage Object Storage resources in your project"
  permissions = [
    # Object Storage
    "storage.buckets.create",
    "storage.buckets.createTagBinding",
    "storage.buckets.delete",
    "storage.buckets.deleteTagBinding",
    "storage.buckets.enableObjectRetention",
    "storage.buckets.get",
    "storage.buckets.getIamPolicy",
    "storage.buckets.getIpFilter",
    "storage.buckets.getObjectInsights",
    "storage.buckets.list",
    "storage.buckets.listEffectiveTags",
    "storage.buckets.listTagBindings",
    "storage.buckets.relocate",
    "storage.buckets.restore",
    "storage.buckets.setIamPolicy",
    "storage.buckets.setIpFilter",
    "storage.buckets.update",
    # Object-level access is required to tear down ClickHouse-managed buckets:
    # bucket deletion runs with force_destroy=true, which must first list and
    # delete the objects inside (e.g. the monitoring bucket's Thanos TSDB
    # blocks) before removing the bucket. Without these, bucket delete 403s and
    # the infra is stuck terminating (BYOC-768).
    "storage.objects.list",
    "storage.objects.get",
    "storage.objects.delete",
    # The Terraform GCS provider lists a bucket's Anywhere Caches before
    # emptying it, and skips the whole force_destroy path when that call is
    # denied — the bucket delete then fails with 409 "not empty" and the object
    # permissions above never come into play. ClickHouse never creates caches,
    # so list access alone is enough to get past the check.
    "storage.anywhereCaches.list",
  ]
}

resource "google_project_iam_custom_role" "clickhouse_iam_role" {
  role_id     = "clickhouseIamRole"
  title       = "ClickHouse IAM Role"
  description = "Role to allow ClickHouse Cloud to manage IAM resources in your project"
  permissions = [
    # Required to grant roles/container.defaultNodeServiceAccount to nodePool SA
    "resourcemanager.projects.setIamPolicy",
    "resourcemanager.projects.getIamPolicy",

    # Manage service accounts
    "iam.serviceAccounts.create",
    "iam.serviceAccounts.createTagBinding",
    "iam.serviceAccounts.delete",
    "iam.serviceAccounts.deleteTagBinding",
    "iam.serviceAccounts.disable",
    "iam.serviceAccounts.enable",
    "iam.serviceAccounts.get",
    "iam.serviceAccounts.getIamPolicy",
    "iam.serviceAccounts.list",
    "iam.serviceAccounts.listEffectiveTags",
    "iam.serviceAccounts.listTagBindings",
    "iam.serviceAccounts.setIamPolicy",
    "iam.serviceAccounts.undelete",
    "iam.serviceAccounts.update",

    # Manage custom roles
    "iam.roles.create",
    "iam.roles.delete",
    "iam.roles.get",
    "iam.roles.list",
    "iam.roles.undelete",
    "iam.roles.update",
  ]
}
